# Generated by Django 4.2 on 2025-09-24 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Temperatura')),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ph')),
                ('condutividade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Condutividade da Agua')),
                ('nivel_racao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nivel Ração')),
                ('horario', models.DateTimeField(verbose_name='Horario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
