# Generated by Django 4.2 on 2025-12-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historico',
            options={'ordering': ['-horario'], 'verbose_name': 'Histórico', 'verbose_name_plural': 'Históricos'},
        ),
        migrations.AlterField(
            model_name='historico',
            name='condutividade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Condutividade da Água (µS/cm)'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='horario',
            field=models.DateTimeField(verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='nivel_racao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nível de Ração (%)'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Temperatura (°C)'),
        ),
    ]
